name: "Sitemap Auto-Sync Protocol V5.0"

on:
  push:
    branches:
      - main  # 仅在主分支 Commit 时触发全球索引更新
    paths:
      - "**.html"            # 网页架构变动
      - "sku-database.json"   # 产品智库变动
      - "generate_sitemap.py" # 逻辑脚本变动
  workflow_dispatch:          # 支持统帅手动强行发射索引

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: "Generate and Notify Sovereign Index"
    permissions:
      contents: write         # 赋予机器人写回仓库的权力

    steps:
      - name: "01_Checkout_Sovereign_Code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "02_Setup_Python_Environment"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: "03_Execute_Custom_Generator"
        run: |
          # 如果统帅有特定的 generate_sitemap.py 逻辑，在此执行
          # 否则该步骤将同步更新 sku-database 映射关系
          if [ -f "generate_sitemap.py" ]; then
            python generate_sitemap.py
          fi

      - name: "04_Generate_Global_Sitemap_XML"
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://yishenglobal.net/
          sitemap-format: xml
          path-to-root: .
          include-pdf: true  # [CRITICAL] 包含资产/文档下的避税与协议 PDF 索引
          additional-extensions: php
          exclude-files: "CNAME, README.md, vercel.json, .gitignore, link_fixer.py"

      - name: "05_Commit_and_Push_Sovereignty_Index"
        run: |
          git config --global user.name "Yishen-Sovereignty-Bot"
          git config --global user.email "bot@yishenglobal.net"
          git add sitemap.xml
          # 只有在索引确实发生物理改变时才进行提交，并使用 [skip ci] 防止无限递归构建
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore(sync): global sovereignty index updated [skip ci]" && git push)

      - name: "06_Notify_Search_Engines"
        run: |
          echo "Sending Sovereign Pulse to Google..."
          curl "https://www.google.com/ping?sitemap=https://yishenglobal.net/sitemap.xml"
          echo "Sending Sovereign Pulse to Bing..."
          curl "https://www.bing.com/ping?sitemap=https://yishenglobal.net/sitemap.xml"
